Add Compilation Changes
gizatechxyz/giza-cli pull request #40
Opened 2024-02-06 13:10 UTC by Gonmeso

This PR aims to make the changes regarding to the compilation included in new versions of the API.

## Current Behaviour
All models were transpiled, but not compilation check at transpilation

## New behaviour
* After transpilation the model is checked for incompatible operators not yet supported in the Transpiler/Orion
* If all the operators are supported the  model is compiled
* If compilation is successful the sierra file is saved at Giza Platform
* Deployments can be deployed without the need of sierra files for fully supported models
* A version which is not fully supported now will be in `PARTIALLY_SUPPORTED` state

2024-02-06 13:27 UTC, franalgaba requested changes

2024-02-06 13:27 UTC, franalgaba commented on giza/frameworks/cairo.py
> +                    echo.warning("🔎 Transpilation is partially supported!")
I would add a more verbose message saying. Its partially support which means some operators of your model are not supported. Go to Orion compatibility to check all the compatible ones and contribute to orion to have its support

2024-02-06 13:27 UTC, franalgaba commented on giza/frameworks/cairo.py
> +    data: Optional[str] = None,
Whats this? Docstring needed?

2024-02-06 13:36 UTC, Gonmeso commented on giza/frameworks/cairo.py
> +    data: Optional[str] = None,
Data is the sierra file, but just left it as `data`will add docstring

2024-02-06 13:39 UTC, Gonmeso commented on giza/frameworks/cairo.py
> +    data: Optional[str] = None,
It is already int he docstring:

`data: main SIERRA file`

2024-02-07 14:06 UTC, franalgaba approved these changes

2024-02-07 14:08 UTC, merged